<?php
define('_DB_SERVER_', '127.0.0.1');
define('_DB_NAME_', 'justc739_devnhamy');
define('_DB_USER_', 'justc739_donuts');
define('_DB_PASSWD_', 'nhamy2013novayork2013');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'cnowwEHuKkvBArPpd50VtBrpVF8S9tsHTbCH89ZnIodMyAssU9WnfzmH');
define('_COOKIE_IV_', 'adoJE6Gq');
define('_PS_CREATION_DATE_', '2012-10-19');
define('_PS_VERSION_', '1.5.6.2');
define('_RIJNDAEL_KEY_', '5uC2VuW9J7ZGAeLp9u27HRAPmGGvEY3p');
define('_RIJNDAEL_IV_', 'v093CmEZVr/p3q4gsIM75A==');
define('_PS_DIRECTORY_', '/../../');
